version: '3.8'

services:
  db:
    image: postgres:13
    container_name: magazinus_db
    environment:
      POSTGRES_DB: magazinus
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=magazinus
    ports:
      - "8000:8000"

volumes:
  db_data:
