version: '3.8'

services:
  # Database service
  db:
    image: postgres:13
    container_name: magazinus_db
    environment:
      POSTGRES_DB: magazinus
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Redis service
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  # ZooKeeper service
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  # Kafka service
  kafka:
    image: bitnami/kafka:2.8.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"

  # User service
  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
      - kafka
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=users
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=magazinus
    ports:
      - "8080:8080"

  # DB Service app
  db_service:
    build:
      context: ./db_service
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=magazinus
    ports:
      - "8000:8000"

volumes:
  db_data:
